---
title: "LFQ comparison"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(dplyr)
library(stringr)
library(limma)
library(PECA)
library(vsn)
library(pROC)
library(kableExtra)
library(ggplot2)
```

## ABRF

Let's define which proteins to examine:

```{r}
# ABRF-1: Beta Galactosidase from E Coli
# ABRF-2: Lysozyme from Gallus gallus
# ABRF-3: Amylase from Aspergillus
# ABRF-4: Protein G Streptococcus
abrfprots <- c("BGAL", "LYSC", "ASPNC", "PROTEING")
```


## FlashLFQ
### Without match-between-runs (no MBR)
```{r}
flash <- read.delim("2019_datasets/ABRF/FLASH_SGPS_Galaxy/flashnoMBR/Galaxy144-[FlashLFQ_on_data_141,_data_140,_and_others__QuantifiedPeptides.tsv].tabular", stringsAsFactors = FALSE)

# Aggregate intensities for each protein and each sample
sapply(abrfprots, function(x){ 
    flash %>% filter(grepl(x,Protein.Groups)) %>%
    group_by(Protein.Groups) %>%
    summarise_if(is.numeric, sum)
  })
```

### With match-between-runs (with MBR)
```{r}
flash_mbr <- read.delim("2019_datasets/ABRF/FLASH_SGPS_Galaxy/flashMBR/Galaxy148-[FlashLFQ_on_data_141,_data_140,_and_others__QuantifiedPeptides.tsv].tabular", stringsAsFactors = FALSE)

# Aggregate intensities for each protein and each sample
sapply(abrfprots, function(x){ 
    flash_mbr %>% filter(grepl(x,Protein.Groups)) %>%
    group_by(Protein.Groups) %>%
    summarise_if(is.numeric, sum)
  })
```


## moFF
### Without match-between-runs (no MBR)

```{r}
# When moFF is run without MBR, we need to combine all of the individual peptide summaries, which we do with `join_all` from `plyr`. 
moff_files <- list.files('2019_datasets/ABRF/moFF_SGPS_Galaxy/moFFnoMBR/peptide_summary-080619/',
                    full.names = TRUE)

moff_no_mbr <- lapply(moff_files, function(i) read.delim(i, as.is = TRUE) %>%
                rename(!!paste("Intensity_",
                     str_extract(i, "ABRF_2016_40Y_1_Sample[0-9_]"), sep="") := sumIntensity_ABRF_PSM_02082019)) %>%
                join_all(by=c("peptide", "prot"), type = "full")

# Aggregate intensities for each protein and each sample
sapply(abrfprots, function(x){ 
    moff_no_mbr %>% filter(grepl(x, prot)) %>%
    group_by(prot) %>%
    summarise_if(is.numeric, sum)
  })
```

### With match-between-runs (with MBR)
```{r}
moff_mbr <- read.delim("2019_datasets/ABRF/moFF_SGPS_Galaxy/moFFMBR/Galaxy9-[moFF_on_data_4,_data_3,_and_others__peptide_summary]-080619.tabular", stringsAsFactors = FALSE)
moff_mbr
# Aggregate intensities for each protein and each sample
sapply(abrfprots, function(x){ 
    moff_mbr %>% filter(grepl(x, prot)) %>%
    group_by(prot) %>%
    summarise_if(is.numeric, sum)
  })
```

## MaxQuant
### Without match-between-runs (no MBR) 
```{r}
maxquant <- read.delim("2019_datasets/ABRF/MaxQuant_GUI/no_MBR/msms.txt", stringsAsFactors = FALSE)
maxquant
```
```{r}
# Aggregate intensities for each protein and each sample
sapply(abrfprots, function(x){ 
    maxquant %>%# select(Raw.file, Proteins, Sequence) %>%
      filter(grepl(x, Proteins))# %>%
    #group_by(Proteins) #%>%
    #summarise_if(is.numeric, sum)
  })
```
```{r}
maxquant
```


### With match-between-runs (with MBR)
```{r}
maxquant_mbr <- read.delim("2019_datasets/ABRF/MaxQuant_GUI/with_MBR/msms.txt", stringsAsFactors = FALSE)
maxquant_mbr
```
```{r}
# Aggregate intensities for each protein and each sample
sapply(abrfprots, function(x){ 
    maxquant_mbr %>% filter(grepl(x, prot)) %>%
    group_by(prot) %>%
    summarise_if(is.numeric, sum)
  })
```


